"""Add tenant_id to chat_users table

Revision ID: add_tenant_id_to_chat_users
Revises: 40b8fa4e4d36
Create Date: 2025-03-17 15:55:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_tenant_id_to_chat_users'
down_revision = '40b8fa4e4d36'  # This should be the ID of the last migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.types.StringUUID(), nullable=True))
        batch_op.create_index(op.f('ix_chat_users_tenant_id'), ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_users', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_chat_users_tenant_id'))
        batch_op.drop_column('tenant_id')
    # ### end Alembic commands ###
