"""Add password field to chat_users table

Revision ID: 4096602f36d6
Revises: 812b1588474a
Create Date: 2025-02-19 15:49:12.129427

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4096602f36d6'
down_revision = '812b1588474a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
