"""Add admin_user_id to chat_users table

Revision ID: add_admin_user_id_to_chat_users
Revises: add_tenant_id_to_chat_users
Create Date: 2025-03-18 13:53:00.000000

"""
from alembic import op
import sqlalchemy as sa
from models.types import StringUUID


# revision identifiers, used by Alembic.
revision = 'add_admin_user_id_to_chat_users'
down_revision = 'add_tenant_id_to_chat_users'  # This should be the ID of your previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('admin_user_id', StringUUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_users', 'admin_user_id')
    # ### end Alembic commands ###
